name: ENV demo
on: workflow_dispatch
env:
  APP_ENV: "Python application"
jobs:
  env_demo:
    runs-on: ubuntu-latest
    steps:
      - name: connect env
        run: echo "This application is a $APP_ENV"
    
