name: if condition
on:
  
jobs:
  Job1:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        if: github.ref_name == 'ain'
        run: echo "Saikiran is tiggered the file" 
      - name: step2
        run: echo "saikiran is a waste fellow"
    
    
      
