name: Inputsparameter
on:
  workflow_dispatch:
    inputs:
      environment:
        description: choose the env to depoloy
        required: true
        default: dev
        type: choice
        options:
          - dev
          - test
          - prod
      artfacts_tags:
        description: choose the env to depoloy
        required: true
        
jobs:
  inputs-demo:
    runs-on: ubuntu-latest
    steps:
      - name: inputsparmeter
        run: echo "depolying the ${{inputs.artfacts_tags}} application to ${{inputs.environment}}"
