name: if condition
on:
  push
jobs:
  Job1:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        if: github.actor == 'aulapathi' || github.actor == 'aulapathi'
        run: echo "Saikiran is tiggered the file............................" 
      - name: step2
        run: echo "saikiran is a waste fellow''''''''''''''''''''''''"
    
    
      
