name: Delopy Html to s3
on: push
jobs:
  Depoly:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from repo
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - name: copying code to s3
        run: |
          aws s3 sync ./ s3://s3bucketforgithubactions/ \
          --exclude "*" \
          --include "imdex.html"
      
